// 由 `scripts/gen_golden.py` 自动生成，请勿手改。
// 32 组用例覆盖 5 种 seed 推导模式 + enchant_randomly / empty /
// 非 chest 表（gameplay）+ blocks / entities / archaeology。

/// 单组用例：(loot_table_id, world_seed, x, y, z, seed, items)。
pub struct GoldenCase {
    pub id: &'static str,
    pub world_seed: i64,
    pub x: i32,
    pub y: i32,
    pub z: i32,
    pub expected_seed: u64,
    pub expected_items: &'static [(&'static str, i32, bool)],
}

pub static GOLDEN_CASES: &[GoldenCase] = &[
    GoldenCase {
        id: "minecraft:chests/ruined_portal",
        world_seed: 12345i64,
        x: 100,
        y: 64,
        z: 200,
        expected_seed: 1400382916045017066u64,
        expected_items: &[
            ("minecraft:golden_helmet", 1, true),
            ("minecraft:flint", 3, false),
            ("minecraft:golden_sword", 1, true),
            ("minecraft:golden_boots", 1, true),
            ("minecraft:golden_leggings", 1, true),
        ],
    },
    GoldenCase {
        id: "minecraft:chests/village/village_weaponsmith",
        world_seed: 12345i64,
        x: 100,
        y: 64,
        z: 200,
        expected_seed: 1400382916045017066u64,
        expected_items: &[
            ("minecraft:obsidian", 3, false),
            ("minecraft:iron_sword", 1, false),
            ("minecraft:iron_sword", 1, false),
            ("minecraft:iron_leggings", 1, false),
        ],
    },
    GoldenCase {
        id: "minecraft:chests/buried_treasure",
        world_seed: 12345i64,
        x: 100,
        y: 64,
        z: 200,
        expected_seed: 852485079u64,
        expected_items: &[
            ("minecraft:heart_of_the_sea", 1, false),
            ("minecraft:gold_ingot", 4, false),
            ("minecraft:iron_ingot", 4, false),
            ("minecraft:iron_ingot", 4, false),
            ("minecraft:iron_ingot", 1, false),
            ("minecraft:iron_ingot", 4, false),
            ("minecraft:gold_ingot", 1, false),
            ("minecraft:emerald", 4, false),
            ("minecraft:diamond", 1, false),
            ("minecraft:iron_sword", 1, false),
            ("minecraft:cooked_salmon", 3, false),
            ("minecraft:cooked_cod", 2, false),
        ],
    },
    GoldenCase {
        id: "minecraft:chests/nether_bridge",
        world_seed: 987654321i64,
        x: 1234,
        y: 70,
        z: -5678,
        expected_seed: 431758787558456u64,
        expected_items: &[
            ("minecraft:golden_horse_armor", 1, false),
            ("minecraft:saddle", 1, false),
            ("minecraft:iron_ingot", 4, false),
        ],
    },
    GoldenCase {
        id: "minecraft:chests/desert_pyramid",
        world_seed: 12345i64,
        x: 100,
        y: 64,
        z: 200,
        expected_seed: 42693636559103u64,
        expected_items: &[
            ("minecraft:golden_horse_armor", 1, false),
            ("minecraft:rotten_flesh", 3, false),
            ("minecraft:gunpowder", 8, false),
            ("minecraft:sand", 5, false),
            ("minecraft:rotten_flesh", 5, false),
            ("minecraft:bone", 5, false),
        ],
    },
    GoldenCase {
        id: "minecraft:chests/stronghold_library",
        world_seed: 42i64,
        x: -200,
        y: 30,
        z: 1500,
        expected_seed: 17717347668657968600u64,
        expected_items: &[
            ("minecraft:book", 2, false),
            ("minecraft:book", 2, false),
            ("minecraft:book", 3, false),
            ("minecraft:paper", 6, false),
            ("minecraft:paper", 2, false),
            ("minecraft:book", 1, false),
            ("minecraft:book", 2, false),
            ("minecraft:paper", 2, false),
            ("minecraft:paper", 6, false),
        ],
    },
    GoldenCase {
        id: "minecraft:chests/end_city_treasure",
        world_seed: 12345i64,
        x: 100,
        y: 64,
        z: 200,
        expected_seed: 42693636559103u64,
        expected_items: &[
            ("minecraft:diamond_pickaxe", 1, false),
            ("minecraft:diamond_sword", 1, false),
            ("minecraft:iron_ingot", 5, false),
        ],
    },
    GoldenCase {
        id: "minecraft:chests/bastion_bridge",
        world_seed: 12345i64,
        x: 100,
        y: 64,
        z: 200,
        expected_seed: 42693636559103u64,
        expected_items: &[
            ("minecraft:lodestone", 1, false),
            ("minecraft:iron_ingot", 4, false),
            ("minecraft:gold_block", 1, false),
            ("minecraft:gold_nugget", 4, false),
            ("minecraft:arrow", 11, false),
            ("minecraft:string", 4, false),
            ("minecraft:arrow", 17, false),
        ],
    },
    GoldenCase {
        id: "minecraft:chests/ancient_city",
        world_seed: 12345i64,
        x: 100,
        y: 64,
        z: 200,
        expected_seed: 42693636559103u64,
        expected_items: &[
            ("minecraft:diamond_horse_armor", 1, false),
            ("minecraft:compass", 1, false),
            ("minecraft:sculk", 6, false),
            ("minecraft:music_disc_cat", 1, false),
            ("minecraft:music_disc_cat", 1, false),
            ("minecraft:book", 2, false),
            ("minecraft:ward_armor_trim_smithing_template", 1, false),
        ],
    },
    GoldenCase {
        id: "minecraft:chests/shipwreck_treasure",
        world_seed: 12345i64,
        x: 100,
        y: 64,
        z: 200,
        expected_seed: 42693636559103u64,
        expected_items: &[
            ("minecraft:emerald", 3, false),
            ("minecraft:iron_ingot", 2, false),
            ("minecraft:emerald", 5, false),
            ("minecraft:iron_nugget", 6, false),
            ("minecraft:iron_nugget", 6, false),
            ("minecraft:iron_nugget", 10, false),
            ("minecraft:gold_nugget", 9, false),
        ],
    },
    GoldenCase {
        id: "minecraft:chests/igloo_chest",
        world_seed: 12345i64,
        x: 100,
        y: 64,
        z: 200,
        expected_seed: 42693636559103u64,
        expected_items: &[
            ("minecraft:rotten_flesh", 1, false),
            ("minecraft:gold_nugget", 1, false),
            ("minecraft:coal", 4, false),
            ("minecraft:golden_apple", 1, false),
        ],
    },
    GoldenCase {
        id: "minecraft:chests/pillager_outpost",
        world_seed: 12345i64,
        x: 100,
        y: 64,
        z: 200,
        expected_seed: 42693636559103u64,
        expected_items: &[
            ("minecraft:potato", 2, false),
            ("minecraft:wheat", 5, false),
            ("minecraft:carrot", 4, false),
            ("minecraft:dark_oak_log", 2, false),
            ("minecraft:dark_oak_log", 3, false),
            ("minecraft:arrow", 7, false),
            ("minecraft:arrow", 7, false),
            ("minecraft:experience_bottle", 1, false),
        ],
    },
    GoldenCase {
        id: "minecraft:chests/ruined_portal",
        world_seed: -1i64,
        x: -100,
        y: 64,
        z: -200,
        expected_seed: 4492368285446091968u64,
        expected_items: &[
            ("minecraft:golden_hoe", 1, true),
            ("minecraft:golden_chestplate", 1, true),
            ("minecraft:flint", 4, false),
            ("minecraft:obsidian", 2, false),
            ("minecraft:flint", 3, false),
            ("minecraft:golden_leggings", 1, true),
            ("minecraft:iron_nugget", 13, false),
            ("minecraft:golden_axe", 1, true),
        ],
    },
    GoldenCase {
        id: "minecraft:chests/simple_dungeon",
        world_seed: 12345i64,
        x: 100,
        y: 64,
        z: 200,
        expected_seed: 22686456163u64,
        expected_items: &[
            ("minecraft:music_disc_13", 1, false),
            ("minecraft:music_disc_cat", 1, false),
            ("minecraft:name_tag", 1, false),
            ("minecraft:redstone", 4, false),
            ("minecraft:bread", 1, false),
            ("minecraft:redstone", 3, false),
            ("minecraft:gunpowder", 1, false),
            ("minecraft:bone", 8, false),
            ("minecraft:bone", 3, false),
        ],
    },
    GoldenCase {
        id: "minecraft:chests/jungle_temple",
        world_seed: 12345i64,
        x: 100,
        y: 64,
        z: 200,
        expected_seed: 42693636559103u64,
        expected_items: &[
            ("minecraft:bone", 5, false),
            ("minecraft:iron_ingot", 2, false),
            ("minecraft:rotten_flesh", 7, false),
        ],
    },
    GoldenCase {
        id: "minecraft:chests/bastion_treasure",
        world_seed: 12345i64,
        x: 100,
        y: 64,
        z: 200,
        expected_seed: 42693636559103u64,
        expected_items: &[
            ("minecraft:ancient_debris", 1, false),
            ("minecraft:diamond_sword", 1, false),
            ("minecraft:diamond_helmet", 1, true),
            ("minecraft:gold_ingot", 9, false),
            ("minecraft:gilded_blackstone", 10, false),
            ("minecraft:crying_obsidian", 4, false),
        ],
    },
    GoldenCase {
        id: "minecraft:chests/abandoned_mineshaft",
        world_seed: 12345i64,
        x: 100,
        y: 64,
        z: 200,
        expected_seed: 42693636559103u64,
        expected_items: &[
            ("minecraft:golden_apple", 1, false),
            ("minecraft:bread", 1, false),
            ("minecraft:coal", 8, false),
            ("minecraft:pumpkin_seeds", 3, false),
            ("minecraft:bread", 2, false),
            ("minecraft:rail", 6, false),
            ("minecraft:detector_rail", 4, false),
            ("minecraft:activator_rail", 4, false),
        ],
    },
    GoldenCase {
        id: "minecraft:chests/village/village_toolsmith",
        world_seed: 12345i64,
        x: 100,
        y: 64,
        z: 200,
        expected_seed: 1400382916045017066u64,
        expected_items: &[
            ("minecraft:stick", 1, false),
            ("minecraft:stick", 2, false),
            ("minecraft:stick", 3, false),
            ("minecraft:bread", 3, false),
        ],
    },
    GoldenCase {
        id: "minecraft:chests/stronghold_crossing",
        world_seed: 42i64,
        x: -200,
        y: 30,
        z: 1500,
        expected_seed: 17717347668657968600u64,
        expected_items: &[
            ("minecraft:gold_ingot", 2, false),
            ("minecraft:coal", 6, false),
            ("minecraft:iron_ingot", 4, false),
            ("minecraft:apple", 3, false),
        ],
    },
    GoldenCase {
        id: "minecraft:chests/stronghold_corridor",
        world_seed: 42i64,
        x: -200,
        y: 30,
        z: 1500,
        expected_seed: 17717347668657968600u64,
        expected_items: &[
            ("minecraft:iron_ingot", 4, false),
            ("minecraft:redstone", 7, false),
            ("minecraft:iron_ingot", 4, false),
        ],
    },
    GoldenCase {
        id: "minecraft:empty",
        world_seed: 0i64,
        x: 0,
        y: 0,
        z: 0,
        expected_seed: 3038984756725240190u64,
        expected_items: &[
        ],
    },
    GoldenCase {
        id: "minecraft:gameplay/fishing",
        world_seed: 12345i64,
        x: 0,
        y: 0,
        z: 0,
        expected_seed: 10328258799079035131u64,
        expected_items: &[
        ],
    },
    GoldenCase {
        id: "minecraft:blocks/diamond_ore",
        world_seed: 12345i64,
        x: 100,
        y: 64,
        z: 200,
        expected_seed: 1400382916045017066u64,
        expected_items: &[
            ("minecraft:diamond_ore", 1, false),
        ],
    },
    GoldenCase {
        id: "minecraft:blocks/oak_leaves",
        world_seed: 12345i64,
        x: 100,
        y: 64,
        z: 200,
        expected_seed: 1400382916045017066u64,
        expected_items: &[
            ("minecraft:oak_leaves", 1, false),
            ("minecraft:stick", 1, false),
            ("minecraft:apple", 1, false),
        ],
    },
    GoldenCase {
        id: "minecraft:blocks/grass_block",
        world_seed: 42i64,
        x: -200,
        y: 30,
        z: 1500,
        expected_seed: 17717347668657968600u64,
        expected_items: &[
            ("minecraft:grass_block", 1, false),
        ],
    },
    GoldenCase {
        id: "minecraft:blocks/ancient_debris",
        world_seed: 987654321i64,
        x: 1234,
        y: 70,
        z: -5678,
        expected_seed: 12851264600016281915u64,
        expected_items: &[
            ("minecraft:ancient_debris", 1, false),
        ],
    },
    GoldenCase {
        id: "minecraft:entities/zombie",
        world_seed: 12345i64,
        x: 100,
        y: 64,
        z: 200,
        expected_seed: 1400382916045017066u64,
        expected_items: &[
            ("minecraft:rotten_flesh", 2, false),
            ("minecraft:iron_ingot", 1, false),
        ],
    },
    GoldenCase {
        id: "minecraft:entities/sheep/blue",
        world_seed: 12345i64,
        x: 100,
        y: 64,
        z: 200,
        expected_seed: 1400382916045017066u64,
        expected_items: &[
            ("minecraft:blue_wool", 1, false),
        ],
    },
    GoldenCase {
        id: "minecraft:entities/cow",
        world_seed: 42i64,
        x: -200,
        y: 30,
        z: 1500,
        expected_seed: 17717347668657968600u64,
        expected_items: &[
            ("minecraft:leather", 0, false),
            ("minecraft:beef", 1, false),
        ],
    },
    GoldenCase {
        id: "minecraft:entities/wither_skeleton",
        world_seed: 987654321i64,
        x: 1234,
        y: 70,
        z: -5678,
        expected_seed: 12851264600016281915u64,
        expected_items: &[
            ("minecraft:coal", -1, false),
            ("minecraft:bone", 1, false),
            ("minecraft:wither_skeleton_skull", 1, false),
        ],
    },
    GoldenCase {
        id: "minecraft:gameplay/piglin_bartering",
        world_seed: 12345i64,
        x: 100,
        y: 64,
        z: 200,
        expected_seed: 1400382916045017066u64,
        expected_items: &[
            ("minecraft:obsidian", 1, false),
        ],
    },
    GoldenCase {
        id: "minecraft:archaeology/desert_pyramid",
        world_seed: 12345i64,
        x: 100,
        y: 64,
        z: 200,
        expected_seed: 1400382916045017066u64,
        expected_items: &[
            ("minecraft:prize_pottery_sherd", 1, false),
        ],
    },
];
